### ISSUE TITLE
Question: shebang for other script languages?

### ISSUE THREAD

**Issue by henrik-jensen** [yousefvand/shellman#12]
Hi @yousefvand and other fellow githubbers
First things first. Great extension -  🥇.
This is more of a question than an issue.
In the first lines in [snippets.json](https://github.com/yousefvand/shellman/blob/71afb82d815e34c384372ae4e5858e8d961424ba/snippets/snippets.json#L2),
```json
...
	"bash": {
    "prefix": "bash",
    "body": "#!/usr/bin/env ${1|bash,node,perl,php,python,python3,ruby|}\n\n",
    "description": "bash shebang"
  },
...
```
the possibility to select other shebangs than 'bash' (or 'sh' which is not present but I think would make sense) have me puzzled?
Shellman is registered as a shell script extension, but when you select, say a perl or a python file, by either giving it the proper extension, `.pl` or `.py`, or using the vscode 'Select Language Mode'-[*Mystery Meat Navigation*](https://en.wikipedia.org/wiki/Mystery_meat_navigation)-"button" ;-), down in the statusbar to select the proper language, the shellman snippets are not activated, because those other languages are not registered in [package.json](https://github.com/yousefvand/shellman/blob/71afb82d815e34c384372ae4e5858e8d961424ba/package.json#L26) so you can't discover or use the snippet in those script languages ?!!!.

I added the shebang snippet for other languages to my user snippets for each language, but I wonder if there are some possibility to incorporate it* in shellman for all the common unix script languages, say awk, sed, perl, python ... i.e. those using '#' as comment char?

*(To be clear, just the shebang part, the other snippets wouldn't make sense for other languages)

**Comment by yousefvand** [comment]
Hello Henrik and thanks for your question.
You are right and that snippet is not legitimate for other languages in `vscode`, since as you said `vscode` would not activate `Shellman` for those languages.
I just put it there to remind users they can use other shebangs for other languages. `Linux` has nothing such as file extension as it exist in `Windows` although many use the same naming convention in `Linux`. So `.py` or any other ending is just part of the file name in `Linux`. You can pass this file name to your language of choice to execute it for you (such as `node`, `python`, `sh`, `perl`...), so to run a `node.js` script:

`$ node /path/to/file.js`

and your operating system knows where to find the full path of `node` by looking in your `PATH` variable.
Using shebang is another way for running your script without telling the OS with engine to use at command line, instead tell OS about the engine at the first line of your script (shebang). Then just making the file executable (consider `file.js` has shebang line):

`$ chmod +x file.js`

Now to run it:

`$ ./file.js`

If I register other languages for just a single snippet (shebang) that would interfere with the language extension/snippet (as user types many non-related bash suggestions come up...) so the best solution now is what you have done (adding it manually to other languages in user snippets) unless `vscode` supports optional snippet syntax for other languages (it can be done as an extension but `Shellman` is a snippet and easy to maintain as snippet rather than extension). When I started `Shellman` `vscode` didn't support multiple prefixes (`"prefix": ["a", "b"]`) but now it does, so maybe it supports in the future to tell `vscode` use a snippet just for some of the registered languages. For now I can change it to:

```
"shebang": {
    "prefix": ["bash", "shebang"],
    "body": "#!/usr/bin/env ${1|bash,sh,node,perl,php,python,python3,ruby|}\n\n",
    "description": "shebang"
  }
```

Any suggestion?

**Comment by henrik-jensen** [comment]
Think it looks good.

One thing to consider though,- I read somewhere, probably ~stackoverflow~ (edit: found it) [stackexchange, on pros. and cons of using `#!/usr/bin/env SOMETOOL`](https://unix.stackexchange.com/a/29620), instead of `#!/usr/bin/SOMETOOL`, that you can't add arguments to a `env bash` (portability issues with some unix's AFAI could understand from [this link in the answer stackexchange](http://www.in-ulm.de/~mascheck/various/shebang/#splitting) ), but honestly haven't tested it. 
FYI: That stackexchange link to ["The #! magic, details about the shebang/hash-bang mechanism on various Unix flavours"](https://www.in-ulm.de/~mascheck/various/shebang) looks like a thorough breakdown of the shebang!

**Comment by yousefvand** [comment]
Thanks for the links. I will make changes in the next release or you can make a pull request and make yourself a contributor to this project.

**Comment by henrik-jensen** [comment]
I'll make some PR's when I've got the time to dig deeper into the subject. My understanding/vision of your extension is that the snippets should represent idiomatic bash/sh code, but that means a bit more research( aka googling ;-) ) and reading before I feel confident for that.
Anyway, I want to shout out that your snippets really is a great productivity tool for me. I'm just juggling with the syntax of to many languages at the moment. so it's such a big help.

**Comment by yousefvand** [comment]
For starter you can make a PR with the change we discussed and add as many shebangs as you wish (in the example code above I have added `sh` as you said. Good luck.
