### ISSUE TITLE
`git clone` snippet for `ssh`

### ISSUE THREAD

**Issue by Haltarys** [yousefvand/shellman#46]
A few years ago, [Github deprecated using HTTPS to clone repositories](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/). Therefore, using SSH is the new default (and a more convenient alternative overall, since it leverages passwordless authentication with SSH keys).

I suggest editing the `git clone` snippet to use the SSH syntax: `git clone git@github.com:username/repository_name` (where the default domain name should be github.com)

Maybe keep the HTTPS snippet for backwards compatibility.

Let me know if you want me to make a PR to fix the issue.

**Comment by yousefvand** [comment]
Hello
A PR is welcome

**Comment by SuperSandro2000** [comment]
> [Github deprecated using HTTPS to clone repositories](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/).

That is completely wrong and not what was announced in the blog post. GitHub deprecated cloning with your user password and you are now required to use a token, oauth or ssh.

There is one major problem which makes cloning via ssh by default bad. It enforces that you must have a ssh key associated with a github account, while https allows you to clone unauthenticated. Also for submodules https should always be used otherwise CI systems cannot clone them since they usually do not have any ssh keys and account attached to it.

If you want to use clone/push via ssh even when https links are used, then gitconfig allows you to rewrite the URL https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf

**Comment by Haltarys** [comment]
@SuperSandro2000 My bad, GitHub deprecated "account passwords when authenticating Git operations" (such as `git push`), not cloning.

I still think cloning using SSH is preferable because it works the same with private repositories. I'd be more comfortable adding a private SSH key to my CI than user/password credentials.

The PR updates the snippets to use SSH syntax, but the HTTPS one is still there (type `git clone https`.) Maybe ask the author to revert it if you think it's worth it. From a bash scripting standpoint, it doesn't make sense to me to have a script that asks for a username/password when run.

The SSH key used for cloning can be changed in your git config :
```ini
[core]
        sshCommand = ssh -i ~/.ssh/id_ed25519
```

**Comment by SuperSandro2000** [comment]
> I still think cloning using SSH is preferable because it works the same with private repositories. I'd be more comfortable adding a private SSH key to my CI than user/password credentials.

If you are using a private repo otherwise https is always preferred because it is guaranteed to always work even when people to not have a github account or an ssh key associated with it.

> The SSH key used by Git can be changed in your git config :
> 
> ```ini
> [core]
>         sshCommand = ssh -i ~/.ssh/id_ed25519
> ```

This is weird, usually you just add something like the following to your gitconfig:

```
Host github.com
  IdentityFile ~/.ssh/id_ed25519
```

**Comment by Haltarys** [comment]
Hello @yousefvand Thank you for accepting my PR. I see that the latest release for the extension is from July 2021. When will the next version come out ?
